# Generated by Django 4.2.10 on 2024-02-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0002_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='zip_cope',
            new_name='zip_code',
        ),
    ]
