# Generated by Django 4.2.10 on 2024-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0005_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
