# Generated by Django 4.2.10 on 2024-02-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerview', '0007_restaurant_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
